adds hardware horn implementation
eclipse-sdv-blueprints/service-to-signal pull request #3
Opened 2024-10-21 13:48 UTC by max-grzanna

This PR introduces a microcontroller-based implementation (actuator-provider) using the ESP32 platform and zenoh-pico.
It serves as an alternative to the software horn, providing a similar functionality for showcasing the horn’s state.

2024-11-01 11:40 UTC, sophokles73 requested changes

2024-11-01 11:40 UTC, sophokles73 commented on README.md
> +As an alternative you can pull the service-to-signal repository directly by executing:
this looks like a duplicate ...

2024-11-01 11:40 UTC, sophokles73 commented on README.md
> +cargo run
duplicate

2024-11-01 11:40 UTC, sophokles73 commented on README.md
> +4. Check logs for Horn
duplicate

2024-11-04 14:36 UTC, max-grzanna commented
I must have overlooked that when rebasing. Thanks for the hint.

2024-11-04 19:42 UTC, sophokles73 approved these changes
LGTM

2024-11-04 19:43 UTC, merged